### ISSUE TITLE
Librechat RAG errors

### ISSUE THREAD

**Issue by FrantaNautilus** [av/harbor#36]
When I tried to submit a document to Librechat, I encountered error. `harbor logs librechat` gives the following output:
```
WARN[0000] The "HARBOR_WHISPER_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HARBOR_WHISPER_HOST_PORT" variable is not set. Defaulting to a blank string. 
harbor.librechat  | }
harbor.librechat  | 2024-09-28 17:21:06 info: [deleteNullOrEmptyConversations] Deleted 0 conversations and 0 messages
harbor.librechat  | 2024-09-28 17:21:11 warn: RAG API is either not running or not reachable at http://lc-rag:33892, you may experience errors with file uploads.
harbor.librechat  | 2024-09-28 17:21:11 info: No changes needed for 'USER' role permissions
harbor.librechat  | 2024-09-28 17:21:11 info: No changes needed for 'ADMIN' role permissions
harbor.librechat  | 2024-09-28 17:21:11 info: 
harbor.librechat  | Outdated Config version: 1.1.5
harbor.librechat  | Latest version: 1.1.7
harbor.librechat  | 
harbor.librechat  |       Check out the Config changelogs for the latest options and features added.
harbor.librechat  | 
harbor.librechat  |       https://www.librechat.ai/changelog
harbor.librechat  | 
harbor.librechat  | 
harbor.librechat  | 2024-09-28 17:21:11 info: Server listening on all interfaces at port 33891. Use http://localhost:33891 to access it
harbor.librechat  | 2024-09-28 17:21:50 error: Failed to fetch models from SGLang API
harbor.librechat  | The request either timed out or was unsuccessful. Error message:
harbor.librechat  |  Cannot read properties of undefined (reading 'status')
harbor.librechat  | 2024-09-28 17:21:59 error: Error embedding file Cannot read properties of undefined (reading 'status')
harbor.librechat  | 2024-09-28 17:21:59 error: [/files] Error processing file: Cannot read properties of undefined (reading 'status')
```
and looking into logs of the RAG container with  I am getting:
```
Traceback (most recent call last):
  File "/app/main.py", line 46, in <module>
    from psql import PSQLDatabase, ensure_custom_id_index_on_embedding, pg_health_check
  File "/app/psql.py", line 3, in <module>
    from config import DSN, logger
  File "/app/config.py", line 5, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```
This problem persists even after manual removal of containers and images and complete "reinstall" of Librechat using `harbor`. The problem seams to be caused by the RAG container, but I could not find if it is caused by the upstream image or configuration.

-------------
I am running harbor version 1.35, on Bluefin DX (Fedora Silverblue 40).

**Comment by pesschap** [comment]
I'm experiencing this issue as well.

**Comment by av** [comment]
Closing as a part of cleanup, please feel free to open a new issue if needed
