### ISSUE TITLE
MCTS in Openweb ui

### ISSUE THREAD

**Issue by bkev** [av/harbor#87]
Does your mcts code still work in Openweb ui or am I doing something wrong? 

In Openweb ui I've gone to Admin Panel --> Functions (across the top) added and enabled it but nothing seems to happen?

Looking at Openweb ui Docker logs I see

"POST /api/v1/functions/id/mcts/toggle HTTP/1.1" 200 OK

INFO [open_webui.apps.ollama.main] get_all_models()

ERROR [open_webui.apps.webui.main] 'State' object has no attribute 'MODELS'

Traceback (most recent call last):

File "/usr/local/lib/python3.11/site-packages/starlette/datastructures.py", line 699, in __getattr__

return self._state[key]

~~~~~~~~~~~^^^^^

KeyError: 'MODELS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/app/backend/open_webui/apps/webui/main.py", line 270, in get_pipe_models

sub_pipes = function_module.pipes()

^^^^^^^^^^^^^^^^^^^^^^^

File "<string>", line 374, in pipes

File "/usr/local/lib/python3.11/site-packages/starlette/datastructures.py", line 702, in __getattr__

raise AttributeError(message.format(self.__class__.__name__, key))

AttributeError: 'State' object has no attribute 'MODELS'

Openweb ui is running in Docker and Ollama on the host, but the models are working in Openweb ui so I don't believe it's a communication issue between Open web UI and Ollama.

**Comment by av** [comment]
Hi, sorry for the long wait! Finally got to debug everything

~Unfortunately, it looks like Open WebUI internals have changed significantly and while it's possible workaround the first issue you mentioned above - it's now unclear how to proxy calls to underlying LLM APIs from the Function source (without breaking things again)~

It almost looked like Open WebUI internals have changed beyound any way to make them compatible with the function again, but I managed to find a few (ugly) workarounds for the mentioned problem and some others. See MCTS v0.0.6 in [Harbor's source](https://github.com/av/harbor/blob/main/open-webui/extras/mcts.py) as well as [Open WebUI Hub](https://openwebui.com/f/everlier/mcts/), tested with Open WebUI v0.5.4

Closing the issue, since this was requested such a long time ago that it's unlikely it's still needed, but please feel free to re-open or follow up otherwise
